
CREATE TABLE GameName (
    GameNameID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    GameName VARCHAR2(50) NOT NULL
);

CREATE TABLE TeamNumber (
    TeamNumberID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TeamName VARCHAR2(50),
    TeamMember01 VARCHAR2(50),
    TeamMember02 VARCHAR2(50),
    TeamMember03 VARCHAR2(50),
    TeamMember04 VARCHAR2(50),
    TeamMember05 VARCHAR2(50),
    TeamMember06 VARCHAR2(50),
    TeamMember07 VARCHAR2(50),
    TeamMember08 VARCHAR2(50),
    TeamMember09 VARCHAR2(50),
    TeamMember10 VARCHAR2(50)
);

CREATE TABLE GameRecord (
    GameRecordID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    GameNameID NUMBER NOT NULL, -- FK
    TeamNumberID NUMBER NOT NULL, -- FK
    Win  NUMBER(1) NOT NULL, -- 0 for false, 1 for true
    Lose NUMBER(1) NOT NULL, -- 0 for false, 1 for true
    Draw NUMBER(1) NOT NULL, -- 0 for false, 1 for true
    -- Define the first foreign key constraint
    CONSTRAINT FK_Game_Name
        FOREIGN KEY (GameNameID)
        REFERENCES GameName(GameNameID),
    -- Define the second foreign key constraint
    CONSTRAINT FK_Team_Number
        FOREIGN KEY (TeamNumberID)
        REFERENCES TeamNumber(TeamNumberID)
);

